# Generated by Django 5.1.4 on 2026-09-27 17:19

import board.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_agentapikey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.CharField(default=board.models._uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Backlog', max_length=200)),
                ('is_default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'backlogs',
                'ordering': ['project_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.CharField(default=board.models._uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('kind', models.CharField(choices=[('worker', 'Worker'), ('assistant', 'Assistant')], default='worker', max_length=32)),
                ('base_url', models.CharField(blank=True, default='', help_text='where to reach it; empty means local-in-process', max_length=300)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('api_key_id', models.ForeignKey(blank=True, help_text='the credential this agent authenticates with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='board.agentapikey')),
            ],
            options={
                'db_table': 'agents',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, help_text='null means any agent may take it', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='board.agent'),
        ),
        migrations.AddField(
            model_name='task',
            name='backlog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='board.backlog'),
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.CharField(default=board.models._uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('projects', 'Projects'), ('backlog', 'Backlog'), ('task', 'Task')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backlog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='board.backlog')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='board.task')),
            ],
            options={
                'db_table': 'chat_sessions',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.CharField(default=board.models._uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('system', 'System')], max_length=16)),
                ('content', models.TextField()),
                ('tool_calls', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='board.agent')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='board.chatsession')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='stable identifier used in URLs; never changes once created', max_length=80, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('repo_url', models.URLField(blank=True, default='')),
                ('is_default', models.BooleanField(default=False, help_text='the project this repository itself; cannot be deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='board.project'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlogs', to='board.project'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, help_text='null only for tasks created before projects existed', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='board.project'),
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_write', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='board.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_memberships',
            },
        ),
        migrations.AddConstraint(
            model_name='chatsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('backlog__isnull', True), ('scope', 'projects'), ('task__isnull', True)), models.Q(('backlog__isnull', False), ('scope', 'backlog'), ('task__isnull', True)), models.Q(('backlog__isnull', False), ('scope', 'task'), ('task__isnull', False)), _connector='OR'), name='chat_scope_anchor_matches'),
        ),
        migrations.AddConstraint(
            model_name='backlog',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('project',), name='uniq_default_backlog_per_project'),
        ),
        migrations.AddConstraint(
            model_name='projectmembership',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='uniq_project_member'),
        ),
    ]
