# Generated by Django 5.1.4 on 2026-09-27 20:24

import board.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_agent_model_probe_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.CharField(default=board.models._new_resource_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('kind', models.CharField(choices=[('host', 'Host (physical or VM)'), ('sandbox', 'Docker sandbox'), ('llm_endpoint', 'LLM endpoint'), ('comfyui', 'ComfyUI endpoint'), ('git_repo', 'Git repository'), ('browser', 'Web browser (Playwright)')], max_length=24)),
                ('lifetime', models.CharField(choices=[('persistent', 'Persistent — exists always'), ('ephemeral', 'Ephemeral — spawned on allocation')], default='persistent', max_length=16)),
                ('description', models.TextField(blank=True, default='')),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'resources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Browser',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.resource')),
                ('image', models.CharField(default='mcr.microsoft.com/playwright:v1.48.0-jammy', max_length=200)),
                ('headless', models.BooleanField(default=True)),
                ('pool_size', models.PositiveIntegerField(default=2)),
            ],
            options={
                'db_table': 'resources_browser',
            },
            bases=('board.resource',),
        ),
        migrations.CreateModel(
            name='ComfyUiEndpoint',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.resource')),
                ('url', models.CharField(max_length=300)),
                ('api_key_cipher', models.TextField(blank=True, default='')),
                ('workflow_timeout_seconds', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resources_comfyui',
            },
            bases=('board.resource',),
        ),
        migrations.CreateModel(
            name='GitRepo',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.resource')),
                ('url', models.CharField(max_length=500)),
                ('default_branch', models.CharField(blank=True, default='main', max_length=120)),
                ('ssh_key_cipher', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'resources_git_repo',
            },
            bases=('board.resource',),
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.resource')),
                ('os_type', models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows')], default='linux', max_length=16)),
                ('hostname', models.CharField(blank=True, default='', max_length=200)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('proto', models.CharField(choices=[('ssh', 'SSH'), ('winrm', 'WinRM'), ('rdp', 'RDP')], default='ssh', max_length=16)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('ssh_key_cipher', models.TextField(blank=True, default='')),
                ('login', models.CharField(blank=True, default='', max_length=80)),
                ('password_cipher', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'resources_host',
            },
            bases=('board.resource',),
        ),
        migrations.CreateModel(
            name='LlmEndpoint',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.resource')),
                ('base_url', models.CharField(max_length=300)),
                ('model_id', models.CharField(blank=True, default='', max_length=200)),
                ('api_key_cipher', models.TextField(blank=True, default='')),
                ('max_tokens', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resources_llm_endpoint',
            },
            bases=('board.resource',),
        ),
        migrations.CreateModel(
            name='Sandbox',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.resource')),
                ('os_type', models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows')], default='linux', max_length=16)),
                ('image', models.CharField(default='ubuntu:22.04', max_length=200)),
                ('cpu_limit', models.FloatField(blank=True, null=True)),
                ('memory_limit_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('hostname', models.CharField(blank=True, default='', max_length=200)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('proto', models.CharField(default='ssh', max_length=16)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('ssh_key_cipher', models.TextField(blank=True, default='')),
                ('login', models.CharField(blank=True, default='', max_length=80)),
                ('password_cipher', models.TextField(blank=True, default='')),
                ('pool_size', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'resources_sandbox',
            },
            bases=('board.resource',),
        ),
        migrations.CreateModel(
            name='ResourceAllocation',
            fields=[
                ('id', models.CharField(default=board.models._new_resource_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('granted', 'Granted'), ('released', 'Released'), ('failed', 'Failed')], default='requested', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('instance_id', models.CharField(blank=True, default='', max_length=200)),
                ('instance_endpoint', models.CharField(blank=True, default='', max_length=300)),
                ('error', models.TextField(blank=True, default='')),
                ('note', models.TextField(blank=True, default='')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_allocations', to='board.agent')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_allocations', to='board.project')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='board.resource')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_allocations', to='board.task')),
            ],
            options={
                'db_table': 'resource_allocations',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status'], name='resource_al_status_524bae_idx'), models.Index(fields=['resource', 'status'], name='resource_al_resourc_006a2d_idx')],
            },
        ),
    ]
