# Generated by Django 5.1.4 on 2026-09-27 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_resource_browser_comfyuiendpoint_gitrepo_host_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentapikey',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='the agent this key was minted for, if any', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='board.agent'),
        ),
        migrations.AlterField(
            model_name='agentapikey',
            name='user',
            field=models.ForeignKey(blank=True, help_text='the account this key acts as; permissions are inherited', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL),
        ),
    ]
