# Generated by Django 5.1.4 on 2026-09-27 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_agentapikey_agent_alter_agentapikey_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='McpServer',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.resource')),
                ('url', models.CharField(blank=True, default='', help_text='HTTP/SSE endpoint URL; ignored when transport=stdio', max_length=500)),
                ('transport', models.CharField(choices=[('http', 'HTTP (JSON-RPC over POST)'), ('sse', 'Server-sent events'), ('stdio', 'stdio (a local process the worker spawns)')], default='http', max_length=8)),
                ('protocol_version', models.CharField(default='2024-11-05', help_text='the MCP protocol version the server speaks', max_length=20)),
                ('api_key_cipher', models.TextField(blank=True, default='')),
                ('declared_tools', models.JSONField(blank=True, default=list, help_text='tools the operator believes this server exposes')),
            ],
            options={
                'db_table': 'resources_mcp_server',
            },
            bases=('board.resource',),
        ),
        migrations.AlterField(
            model_name='resource',
            name='kind',
            field=models.CharField(choices=[('host', 'Host (physical or VM)'), ('sandbox', 'Docker sandbox'), ('llm_endpoint', 'LLM endpoint'), ('comfyui', 'ComfyUI endpoint'), ('git_repo', 'Git repository'), ('browser', 'Web browser (Playwright)'), ('mcp_server', 'MCP server (Model Context Protocol)')], max_length=24),
        ),
    ]
